# Generated by Django 5.2.8 on 2025-11-10 20:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Administrador del sistema', 'Administrador del sistema'), ('Instructor', 'Instructor'), ('Coordinador de área', 'Coordinador de área'), ('Funcionario de bienestar', 'Funcionario de bienestar'), ('Aprendiz', 'Aprendiz')], help_text='Rol asignado al usuario dentro del sistema.', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción general del rol y sus responsabilidades.', null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, help_text='Rol asignado al usuario (p. ej. Aprendiz, Instructor).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuario.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('nivel_educativo', models.CharField(max_length=50)),
                ('grupo_etnico', models.CharField(max_length=50)),
                ('estrato', models.PositiveSmallIntegerField()),
                ('barrio', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=10)),
                ('ocupacion', models.CharField(max_length=50)),
                ('tiene_hijos', models.BooleanField(default=False)),
                ('cantidad_hijos', models.CharField(blank=True, max_length=20, null=True)),
                ('con_quien_vive', models.CharField(max_length=50)),
                ('cabeza_hogar', models.CharField(max_length=50)),
                ('tipo_vivienda', models.CharField(max_length=50)),
                ('num_personas_hogar', models.CharField(max_length=20)),
                ('acceso_internet', models.BooleanField(default=False)),
                ('equipo_propio', models.BooleanField(default=False)),
                ('responsable_hogar', models.BooleanField(default=False)),
                ('apoyo_formacion', models.BooleanField(default=False)),
                ('apoyo_emocional', models.BooleanField(default=False)),
                ('distancia_centro', models.CharField(max_length=20)),
                ('medio_transporte', models.CharField(max_length=50)),
                ('tiempo_desplazamiento', models.CharField(max_length=30)),
                ('dificultad_transporte', models.BooleanField(default=False)),
                ('costo_transporte', models.BooleanField(default=False)),
                ('programa', models.CharField(max_length=150)),
                ('motivo_programa', models.TextField(blank=True, null=True)),
                ('apoyos_necesarios', models.TextField(blank=True, null=True)),
                ('ha_pensado_dejar', models.BooleanField(default=False)),
                ('motivos_dificultad', models.TextField(blank=True, null=True)),
                ('apoyos_externos', models.BooleanField(default=False)),
                ('apoyos_suficientes', models.BooleanField(default=False)),
                ('jornada', models.CharField(max_length=20)),
                ('dificultades_actuales', models.CharField(max_length=100)),
                ('etapa_dificil', models.CharField(max_length=50)),
                ('apoyo_necesario', models.CharField(max_length=50)),
                ('horas_estudio_fuera', models.CharField(max_length=20)),
                ('prob_finalizacion', models.CharField(max_length=20)),
                ('afiliacion_eps', models.BooleanField(default=False)),
                ('condicion_salud', models.CharField(blank=True, max_length=200, null=True)),
                ('condicion_psicologica', models.BooleanField(default=False)),
                ('apoyo_psicologico', models.BooleanField(default=False)),
                ('necesita_apoyo_salud', models.BooleanField(default=False)),
                ('cambios_emocionales', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(max_length=20)),
                ('ansiedad_estres', models.CharField(max_length=20)),
                ('influencia_emociones', models.CharField(max_length=20)),
                ('concentracion', models.CharField(max_length=20)),
                ('tiene_dispositivo', models.BooleanField(default=False)),
                ('dificultad_internet', models.BooleanField(default=False)),
                ('comparte_dispositivo', models.CharField(max_length=50)),
                ('presion_programa', models.BooleanField(default=False)),
                ('decision_programa', models.CharField(max_length=200)),
                ('piensa_ejercer', models.BooleanField(default=False)),
                ('desea_apoyo_emocional', models.BooleanField(default=False)),
                ('entorno_valora', models.BooleanField(default=False)),
                ('entorno_positivo', models.BooleanField(default=False)),
                ('victima_discriminacion', models.CharField(max_length=100)),
                ('desplazamiento_conflicto', models.BooleanField(default=False)),
                ('dano_familiar_conflicto', models.CharField(max_length=50)),
                ('impacto_conflicto', models.CharField(max_length=50)),
                ('dificultad_pedir_ayuda', models.CharField(max_length=50)),
                ('influencia_conflicto_familiar', models.CharField(max_length=50)),
                ('impacto_perdida', models.CharField(max_length=50)),
                ('nivel_riesgo', models.CharField(blank=True, max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
