# Generated by Django 5.2.8 on 2025-11-13 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'coordinador_area_area',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionInstructorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_instructores', to='coordinador_area.area')),
                ('coordinador', models.ForeignKey(help_text='Usuario que tiene rol Coordinador de área.', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_areas_como_coordinador', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(help_text='Usuario que tiene rol Instructor.', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_areas_como_instructor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Instructor a Área',
                'verbose_name_plural': 'Asignaciones de Instructores a Áreas',
                'db_table': 'coordinador_area_asignacion_instructor_area',
                'constraints': [models.UniqueConstraint(fields=('instructor', 'area'), name='unique_instructor_area')],
            },
        ),
    ]
